# Generated by Django 5.2.8 on 2025-11-07 17:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChaiVerity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='chais/')),
                ('date_added', models.DateTimeField(default=datetime.datetime(2025, 11, 7, 17, 0, 4, 760634, tzinfo=datetime.timezone.utc))),
                ('chai_type', models.CharField(choices=[('ML', 'MASALA'), ('GR', 'GINGER'), ('KI', 'KIWI'), ('EL', 'ELAICHI')], max_length=2)),
            ],
        ),
    ]
