# Generated by Django 5.2.8 on 2025-11-07 21:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chai', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chaiverity',
            name='date_added',
            field=models.DateTimeField(default=datetime.datetime(2025, 11, 7, 21, 11, 55, 431728, tzinfo=datetime.timezone.utc)),
        ),
    ]
