# Generated by Django 5.2.8 on 2025-11-07 21:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chai', '0002_alter_chaiverity_date_added'),
    ]

    operations = [
        migrations.AddField(
            model_name='chaiverity',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='chaiverity',
            name='date_added',
            field=models.DateTimeField(default=datetime.datetime(2025, 11, 7, 21, 36, 51, 751798, tzinfo=datetime.timezone.utc)),
        ),
    ]
