# Generated by Django 5.2.8 on 2025-11-07 21:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chai', '0003_chaiverity_description_alter_chaiverity_date_added'),
    ]

    operations = [
        migrations.AddField(
            model_name='chaiverity',
            name='price',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='chaiverity',
            name='date_added',
            field=models.DateTimeField(default=datetime.datetime(2025, 11, 7, 21, 52, 4, 351536, tzinfo=datetime.timezone.utc)),
        ),
    ]
